### ISSUE TITLE
Long term solution for URL regression

### ISSUE THREAD

**Issue by kali** [snipsco/dinghy#101]
see #97 

Consider patching url upstream.

**Comment by MarcTreySonos** [comment]
as the post-release.sh is running cargo update:  
https://github.com/snipsco/dinghy/blob/b4500f3b3e9d2939efef9c1878963fa8f0ea6598/post-release.sh#L27

the url regression is back into master https://github.com/snipsco/dinghy/pull/97#issuecomment-580805652

**Comment by kali** [comment]
Reopened, we will probably have to un-freeze this version at some point in the future, so we need url to be patched upstream.

**Comment by Deluvi** [comment]
Fixed by #111
