### ISSUE TITLE
make_linux_app is creates more and more files each time

### ISSUE THREAD

**Issue by dten** [snipsco/dinghy#19]
`make_linux_app` copies the root of a project into `target/deps/dinghy/dinghy` for some reason

it also copies target, which contains the previous copy, so now you have two, next time you'll have three, and so on.

not sure best way to fix it but thought i'd let you know :)

**Comment by kali** [comment]
that's interesting indeed :) I'll have soon-ish. Thanks :)

**Comment by dten** [comment]
this line is doing the same for ios apps and it's causing me to hit max path https://github.com/snipsco/dinghy/blob/master/src/ios/xcode.rs#L39

commenting out that line and it's alive again

**Comment by kali** [comment]
Ok, by any chance, do you happen not to have a .gitignore file around that skips target ? I think this is the reason why you got in trouble, as dinghy uses https://docs.rs/ignore/0.1.9/ignore/ to guess what to copy (to target/ first, and then to the device).

Removing it on one of my project leads to absurd behaviour of a different kind, but still aberrant (infinite loop while copying stuff in target).

I think the best way to go is a fix that explicitely ignores target/, but it would be nice if you could confirm the absence of .gitignore in your project.

**Comment by dten** [comment]
I don't have one because that project uses hg not git
Guess I'll do more yak shaving and add hg support to ignore :p
I think for people who use other things though target should definitely be filtered regardless

**Comment by kali** [comment]
yep, doing that right now.

**Comment by kali** [comment]
thanks for confirming the bug

**Comment by dten** [comment]
Why does the android one copy the files by the way? I don't see that it does anything with them.

**Comment by kali** [comment]
you do not require them per se... but many times, tests rely on the presence of test data in a separate file that is read by the test.
So the strategy is to copy the project code in a predictable place, and have the test checking the environment to know where to look for.

**Comment by kali** [comment]
i have pushed a 0.2.8 that will always ignore /target/. I'm pretty sure this will bite me some day, but I'll deal with it at that time :)

**Comment by dten** [comment]
well it gets further, but i get a failure trying to run the tests on android cause dinghy is a dir not an executable

**Comment by dten** [comment]
if you're looking at this don't worry. i was working on a PR and have fixed it in that :)
