### ISSUE TITLE
Allow specifying port number for ssh

### ISSUE THREAD

**Issue by azdlowry** [snipsco/dinghy#26]
I have ssh on port other than 22 so need to allow it to be overridden.

I have a branch with this change in, just waiting for my previous PR to be merged before submitting.

**Comment by fredszaq** [comment]
Hi ! 
we're currently using the general ssh conf for that, ie creating a section that in you `~/.ssh/config` that looks like that :
```
Host dev
    HostName dev.example.com
    Port 22000
    ...
```
no sure how far we should replicate the ssh conf in dinghy (but seems to be a frequent enough option to have its place here)
