### ISSUE TITLE
Error installing dinghy

### ISSUE THREAD

**Issue by gnzlbg** [snipsco/dinghy#36]
It seems that dinghy currently doesn't build:

```shell
error[E0283]: type annotations required: cannot resolve `std::path::Component<'_>: std::convert::AsRef<_>`
   --> src/lib.rs:152:46
    |
152 |         if path.components().any(|comp| comp.as_ref() == "target" ) {
    |                                              ^^^^^^

error: aborting due to previous error

error: failed to compile `dinghy v0.2.15`, intermediate artifacts can be found at `/var/folders/mm/y444qqwd0kn52fycyz6nsph40000gn/T/cargo-install.m0ljJEc7Mo0Q`

Caused by:
  Could not compile `dinghy`.
```

**Comment by kali** [comment]
Interesting, it does compile on my side. Can i ask what version of rustc you're using ?

**Comment by gnzlbg** [comment]
Rust nightly from yesterday, you?

**Comment by kali** [comment]
I tend to use a relatively recent stable for dinghy. Can reproduce with nightly, looking for a fix.

**Comment by gnzlbg** [comment]
Maybe you could add a nightly build bot to travis, and enable the travis "cron job" feature to automatically rebuild master every 24 h. You can also mark this build bot as `allowed_failures:` to allow it to fail, but that way it will be at least easy to check when nightly breaks something :)

**Comment by kali** [comment]
Well, I do have a nightly build on travis, and I saw it break once in a while. Most of the time it gets fixed in the next nightly, before i took the time to have a look...

**Comment by gnzlbg** [comment]
ah :D Thanks for the commit and the fix! that was really quick!
