### ISSUE TITLE
Refactoring some common logic into a library

### ISSUE THREAD

**Issue by learnopengles** [snipsco/dinghy#4]
Hi,

Would you be open to a PR where I factor some code out into a common sub-crate? Or alternatively I would just create a new git repo and then I could submit a PR request to dinghy to use some of the shared logic?

After chatting with Alex from the Rust team, it seems they'd much prefer I put all the logic in Rust rather than Python, so by doing this we'd be able to use that logic in dinghy but also in the rust compiler.

Alternatively I could just copy/paste instead of creating a dependency in Dinghy; the code is small enough that I guess that would be OK too.

**Comment by kali** [comment]
Hi, 

What are you trying to achieve with the rust test suite exactly ? What specific parts of dinghy do you want to share with rust test suite, and which part would you prefer to exclude ? What about using dinghy itself as a library, just like cargo-dighy does and take it from there ?

In terms of sharing VS cut and pasting, there are other factor to consider. On principle, sharing would undoubtly be better. On the other hand, Dinghy code is young, still feels clunky, and is probably fragile in ways I have no idea about. Putting it as-is under the strict-ish code management suitable for rustc may be a bit premature.

**Comment by learnopengles** [comment]
Hi Mathieu! Basically I would need the deployment + execution part of dinghy, but not the compiling. Right now it would just be for the simulator. I think your idea on "What about using dinghy itself as a library, just like cargo-dighy does and take it from there ?" makes a lot of sense.

As an example here's how I did it for libc: https://github.com/rust-lang/libc/pull/498/files

**Comment by kali** [comment]
Hi, is this topic still active ? Have you tried moving some logic already ? or should we just close this ?

**Comment by learnopengles** [comment]
Hi Mathieu, sorry, I didn't have email notifications enabled apparently. I haven't been writing Rust for mobile so I haven't really spent much time on it. 😇 So yes, we could just close this for now.

It would still be neat to do, and when we were discussing this I submitted a PR to rust-lang/libc a while ago that added support to the libc library: https://github.com/rust-lang/libc/pull/498/commits. I suppose something similar would work for the main repo.
