### ISSUE TITLE
Should benchmarks return performance numbers?

### ISSUE THREAD

**Issue by pitdicker** [snipsco/dinghy#44]
I just set up testing `rand` with `dinghy`. Installing the android sdk and dinghy was reasonably easy!

`cargo dinghy test` works as expected, and all tests pass :smile:.

But is `cargo dinghy bench` only expected to run benchmarks as tests, returning `ok` instead of performance numbers? Asking here just in case this is intended before looking much further.

My system: Fedora Linux, with `adb` from Fedora, and a downloaded `android-ndk-r16b`. My phone is an Android Motorola G3, and for `rust` I am using the latest nightly, but also no luck with a nightly from three months ago.

**Comment by ratamovic** [comment]
I guess you are using the master version of Dinghy? Could you give a try to the latest version, that we are currently working on to see if it works better for you?
You can install it with the following command 'cargo install --force --git 'https://github.com/snipsco/dinghy.git' --branch 0.3'
Beware that configuration might change a little bit and that ndk is not directly supported anymore (they are replaced with standalone toolchains instead).

**Comment by pitdicker** [comment]
Thank you for the quick reply.

I have installed the latest version of Dinghy, build a standalone toolchain and created `dinghy.toml` and `.cargo/config` files to point to the toolchain and linker. (That took care of the error "Couldn't find toolchain directory).

But somehow all tests are now run locally, not on my phone. Have I missed a piece of the configuration?
```
[pitdicker@localhost rand]$ adb devices
List of devices attached
ZY2239VRK2	device

[pitdicker@localhost rand]$ cargo dinghy devices
List of available devices for platform 'host':
Host { }
```

**Comment by ratamovic** [comment]
Dinghy also builds on host now by default. Just add `--platform <your platform name>` between `cargo dinghy` and `build test or bench`.

For example if you have the following in your ~/.dinghy/dinghy.toml (As explained in the [Readme](https://github.com/snipsco/dinghy/tree/0.3)):
```
[platforms.android-armv7]
rustc_triple="armv7-linux-androideabi"
toolchain="<path to your armv7-linux-androideabi standalone toolchain>"
```
Then you can call `cargo dinghy --platform android-armv7 build`

**Comment by pitdicker** [comment]
I had to install the latest version of `adb` instead of the one that came with Fedora because `--sync` was not working. The tests now run again!

But benchmarks still only give `ok` as result instead of measurements...
```
cargo dinghy --platform android-armv7 bench
```

**Comment by kali** [comment]
Hi, thanks for the report, we have pushed a fix on the 0.3 branch. Feel free to try it :)

**Comment by pitdicker** [comment]
Thanks for the fix! But I don't have luck with it yet, the benchmarks still only print `ok`... Is there any information I can give to help?

**Comment by kali** [comment]
Indeed, I fixed ssh and not android. Sorry. Just pushed again :)

**Comment by pitdicker** [comment]
It works, thank you very much!
