### ISSUE TITLE
Error when I try to use dinghy

### ISSUE THREAD

**Issue by tiby312** [snipsco/dinghy#48]
```
ken@ken-XPS-13-9360:~/rust/dinotree$ cargo dinghy build
No such file or directory (os error 2)

```

dinghy devices correctly shows android device.

**Comment by kali** [comment]
Hi ! Thanks for the report.

What platform is your workstation ? Is the project you are trying to build publicly available somewhere ?

Can you run adding "-v" right after "dinghy" (or even "-vv" or "-vvv") to get more information ?

**Comment by tiby312** [comment]
I'm using ubuntu. I tried running dinghy on the dinghy tests instead of my own project, and same issue. It can't find the -v or -d command. I have to do -device. I wonder if the version of dinghy that cargo installed is out of date?

**Comment by tiby312** [comment]
Yeah that got me further. Now I'm getting a different error I haven't researched yet.
```
   Finished release [optimized] target(s) in 29.88 secs
 ERROR cargo_dinghy > Error: Error syncing android directory ("/usr/bin/adb" "-s" "ZY223ZTPWZ" "push" "--sync" "/home/ken/rust/dinotree_inner/target/armv7-linux-androideabi/release/dinghy/dinotree_inner-fd4e42d5e4a07169" "/data/local/tmp/dinghy")

Error: Error syncing android directory ("/usr/bin/adb" "-s" "ZY223ZTPWZ" "push" "--sync" "/home/ken/rust/dinotree_inner/target/armv7-linux-androideabi/release/dinghy/dinotree_inner-fd4e42d5e4a07169" "/data/local/tmp/dinghy")

```

**Comment by tiby312** [comment]
I meant to say that I cloned the repo instead of using rustup

**Comment by kali** [comment]
From the form of your ERROR output, you are using the last version, or the one from yesterday, so that part should be fine.

`cargo install` should install 0.3.1, the current version, but you need to add "-f" in order to overwrite a previously installed one.

can you try running the `adb` command from the shell directly ?

```
"/usr/bin/adb" "-s" "ZY223ZTPWZ" "push" "--sync" "/home/ken/rust/dinotree_inner/target/armv7-linux-androideabi/release/dinghy/dinotree_inner-fd4e42d5e4a07169" "/data/local/tmp/dinghy"
```

**Comment by tiby312** [comment]
```
ken@ken-XPS-13-9360:~/rust/dinotree$ adb" "-s" "ZY223ZTPWZ" "push" "--sync" "/home/ken/rust/dinotree/target/armv7-linux-androideabi/release/dinghy/dinotree-a8b9a9a17ad02ace" "/data/local/tmp/dinghybash: adb -s ZY223ZTPWZ push --sync /home/ken/rust/dinotree/target/armv7-linux-androideabi/release/dinghy/dinotree-a8b9a9a17ad02ace /data/local/tmp/dinghy: No such file or directory
ken@ken-XPS-13-9360:~/rust/dinotree$ ls /home/ken/rust/dinotree/target/armv7-linux-androideabi/release/dinghy/dinotree-a8b9a9a17ad02aceCargo.toml  dinotree-a8b9a9a17ad02ace  examples  readme.md  src  test_data

```

Does the folder /data/local/tmp/dinghy need to exist? Maybe I dont have permissions to make it?

**Comment by kali** [comment]
You got the quotes wrong, here, and it's just bash erroring because it can't find an executable named "adb -s ZY223ZTPWZ push --sync /home/ken/rust/dinotree/target/armv7-linux-androideabi/release/dinghy/dinotree-a8b9a9a17ad02ace /data/local/tmp/dinghy"

Either pick *all* the quotes from my previous line, or none of them, but what you tried here can't work :)

**Comment by tiby312** [comment]
Oops my bad. I got this:
```
ken@ken-XPS-13-9360:~/rust/dinotree_inner$ "/home/ken/android-sdk/platform-tools/adb" "-s" "ZY223ZTPWZ" "push" "--sync" "/home/ken/rust/dinotree_inner/target/armv7-linux-androideabi/release/dinghy/dinotree_inner-fd4e42d5e4a07169" "/data/local/tmp/dinghy"
adb: unrecognized option '--sync'
```

**Comment by tiby312** [comment]
Ah! turns out my adb was out of date. I updated it using the sdkmanager utility and it worked. Thanks!

**Comment by kali** [comment]
Good. Everything working now ? OK to close ?

**Comment by tiby312** [comment]
Yup. Thanks again
