### ISSUE TITLE
unresolved name `ensure_shim` when trying to cargo install

### ISSUE THREAD

**Issue by hsivonen** [snipsco/dinghy#5]
## Steps to reproduce

Run `cargo install dinghy` on Ubuntu 16.04 with either stable (1.14.0) or nightly (1.16.0-nightly 2017-01-17).

## Actual results

```
error[E0425]: unresolved name `ensure_shim`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/dinghy-0.1.9/src/build.rs:102:5
    |
102 |     ensure_shim(device_target)?;
    |     ^^^^^^^^^^^ unresolved name

error[E0425]: unresolved name `ensure_shim`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/dinghy-0.1.9/src/build.rs:127:5
    |
127 |     ensure_shim(device_target)?;
    |     ^^^^^^^^^^^ unresolved name

error[E0425]: unresolved name `ensure_shim`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/dinghy-0.1.9/src/build.rs:152:5
    |
152 |     ensure_shim(device_target)?;
    |     ^^^^^^^^^^^ unresolved name
```

## Expected results

Successful build.

**Comment by kali** [comment]
all right, I've obviously missed something here :)

I've pushed a quick fix on master. Would you like to give it a try ? (just checkout and run `cargo install`)

**Comment by kali** [comment]
Setting up travis right now, so I should not break linux unknowingly.

**Comment by kali** [comment]
I've pushed to crates the new version.

**Comment by hsivonen** [comment]
0.1.10 from crates.io builds now. (Tested on nightly.) Thank you.
