### ISSUE TITLE
Fails to sign when there is any non .mobileprovision file in Profiles folder

### ISSUE THREAD

**Issue by vhnatyk** [snipsco/dinghy#77]
Hi! **I'm blessed to find this amazing tool folks and I can't tell how thankful I am:)**! 

However, there is an issue that puzzled me for a day to the point I almost gave up. If there is any file (that is not provision profile) or folder with update date higher then our Dinghy provisioning profile, then it fails with not too descriptive Rust error "**failed to fill whole buffer**". 

So for example if you view the folder with Finder (like we - guys coming from Windows - usually do with visual tools and not cmd :D ), then .DS_Store file is always updated or if you happen to create some folder to backup some profiles - anything that is not signing profile with higher date will cause Dinghy to read it first and exit with the confusing error message.

I will try to do the PR for the fix - it's in xcode.rs:124, but if you'd be faster to fix, I won't be jealous I promise since I'm pretty new to Rust.

Again many thanx for the great tool.

You guys rock!

**Comment by kali** [comment]
Thanks for the report and the kind words !

As you can see, the fix is hopefully on its way, I will cut a new version right away.

**Comment by kali** [comment]
Hey, could you confirm the latest release fix your issue ?

**Comment by vhnatyk** [comment]
Hi - sorry for delay fixed, but there is another related issue regarding auto-signing profiles
